In [1]:
import numpy as np

In [5]:
a=np.array([[2,-1,5,-3],
           [4,1,2,-1],
           [4,1,-3,-8],
           [3,6,-1,2]],float)

In [4]:
b=np.array([3,2,2,-1],float)

In [9]:
from scipy.linalg import solve,inv
x=solve(a,b)
x

array([ 0.36500754, -0.23378582,  0.28506787, -0.20361991])

In [13]:
#Also can use inv to solve the linear equation
x=np.dot(inv(a),b)
x

array([ 0.36500754, -0.23378582,  0.28506787, -0.20361991])

In [16]:
#Numpy also can solve for linear equation
x=np.linalg.solve(a,b)
x

array([ 0.36500754, -0.23378582,  0.28506787, -0.20361991])